import Head from "next/head";
import Image from "next/image";
import MyHead from "../components/MyHead";
import Navbar from "../components/Navbar";
import Project from "../components/Project";
import ProjectContainer1 from "../components/ProjectContainer1";
export default function Home() {
  return (
    <div className="">
      <Head>
        <title>My Projects</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/images/favicon.ico" />
      </Head>
      <MyHead />
      <Navbar />
      <ProjectContainer1 />
    </div>
  );
}
