import Head from "next/head";
import React from "react";
import Navbar from "../components/Navbar";
import ProjectContainer4 from "../components/ProjectContainer4";

const normal = () => {
  return (
    <div>
      <Head>
        <title>Normal Projects</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/images/favicon.ico" />
      </Head>
      <Navbar />
      <ProjectContainer4 />
    </div>
  );
};

export default normal;
