import Head from "next/head";
import React from "react";
import Navbar from "../components/Navbar";
import ProjectContainer2 from "../components/ProjectContainer2";

const reactjs = () => {
  return (
    <div>
      <Head>
        <title>ReactJS Projects</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/images/favicon.ico" />
      </Head>
      <Navbar />
      <ProjectContainer2 />
    </div>
  );
};

export default reactjs;
